name: PICO2W_W5500_Vegleges
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kód letöltése
        uses: actions/checkout@v4

      - name: Telepítések
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-none-eabi build-essential cmake python3-pyelftools

      - name: mpy-cross fordítása
        run: make -C mpy-cross

      - name: W5500 és minden hiányzó modul letöltése
        run: git submodule update --init --recursive

      - name: Fordítás indítása
        run: |
          cd ports/rp2
          make BOARD=RPI_PICO2_W clean
          make BOARD=RPI_PICO2_W submodules
          make BOARD=RPI_PICO2_W

      - name: Kész fájl kimentése
        uses: actions/upload-artifact@v4
        with:
          name: pico2w-w5500-firmware
          path: ports/rp2/build-RPI_PICO2_W/firmware.uf2
